site_name: Bulk Products
site_url: http://localhost:8001
strict: true
nav:
  - Главная: index.md
  - Установка: installation.md
  - Быстрый старт: start.md
  - Настройка модуля: settings.md
  - 'Фильтрация и выбор товаров':
      - Фильтры: product-search/filters.md
      - Выбор товаров: product-search/select.md
  - 'Редактирование товаров':
      - product-bulk-edit/index.md
      - 'Название товара': product-bulk-edit/product_name.md
      - 'Цена': product-bulk-edit/product_price.md
      - 'Производитель': product-bulk-edit/product_manufacturer.md
      - 'Категории': product-bulk-edit/product_categories.md
      - 'Главная категория': product-bulk-edit/product_main_category.md
      - 'Описание': product-bulk-edit/product_description.md
      - 'HTML-тег H1': product-bulk-edit/product_meta_h1.md
      - 'Мета-тег Title': product-bulk-edit/product_meta_title.md
      - 'Мета-тег Description': product-bulk-edit/product_meta_description.md
      - 'Мета-тег Keywords': product-bulk-edit/product_meta_keywords.md
      - 'Код товара': product-bulk-edit/product_model.md
      - 'Количество': product-bulk-edit/quantity.md
      - 'Статус товара': product-bulk-edit/product_status.md
      - 'Скидки': product-bulk-edit/product_discounts.md
      - 'Модификаторы': product-bulk-edit/modificators.md
      - 'Переменные': product-bulk-edit/variables.md
  - 'Инструмент SEO Master':
      - seo-master/index.md
      - 'Ручной режим': seo-master/manually.md
      - 'AI Powered': seo-master/ai-powered.md
  - 'Удаление товаров':
      - product-bulk-delete/index.md
  - 'Предпросмотр изменений':
      - simulation/index.md
  - 'Применение изменений':
      - bulk-process/index.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption

theme:
  name: material
  language: ru
  features:
    - glightbox
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - navigation.top
    - glightbox
    - navigation.instant

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

extra:
  analytics:
    provider: google
    property: G-PV23YD5H71